export const MESSAGE_REQUEST = "MESSAGE_REQUEST";
export const NEW_MESSAGE_RECEIVED = "NEW_MESSAGE_RECEIVED";
export const SERVER_CONNECTION_REQUESTED = "SERVER_CONNECTION_REQUESTED";
export const CONNECTED_TO_SERVER = "CONNECTED_TO_SERVER";
export const DISCONNECTED_FROM_SERVER = "DISCONNECTED_FROM_SERVER";
export const SERVER_ERROR = "SERVER_ERROR";
export const SET_USER = "SET_USER";
